### ISSUE TITLE
Use static code analysis

### ISSUE THREAD

**Issue by if1live** [amitu/importd#53]
from #52.

## Manual static code analysis
* pylint
* PEP257
* autopep8
* etc?

Run on command line. It is simple, but we can't track quality of code. 
Can we say that "today code is better than yesterday code"? 
We cannot answer to this question. We can't remember all past code analysis results.

## Automatic static code analysis
landscape.io is static code analysis service for python. https://landscape.io/
sample : https://landscape.io/github/sueastside/django-project

It is similar with PEP8 or pylint. But we can track quality of code.

**Comment by amitu** [comment]
Done. Thanks a lot @if1live :-)
