### ISSUE TITLE
importd without middleware classes defined admin don't work

### ISSUE THREAD

**Issue by santagada** [amitu/importd#64]
a minimal example is:

```
$ cat l.py
from importd import d

if __name__ == '__main__':
	d.main()
```

when you try to access the admin you receive:

```python
AttributeError at /admin/
'WSGIRequest' object has no attribute 'user'
```

You need to declare auth related middlewares for it to work.

**Comment by akshar-raaj** [comment]
I just started with this project. I am not aware of architecture of this project and if there is plan to add default middleware classes for admin to work.

But until default middleware classes are added, adding these two lines will make admin work

from importd import d

d(MIDDLEWARE_CLASSES=['django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware'])

**Comment by juancarlospaco** [comment]
Interesting should be to integrate the know solutions into the actual code on master, via a Pull Request
:smile_cat:

**Comment by akshar-raaj** [comment]
@juancarlospaco I will give it a try now and open a PR

**Comment by juancarlospaco** [comment]
:shipit:

**Comment by akshar-raaj** [comment]
@juancarlospaco Opened a PR https://github.com/amitu/importd/pull/70
