### ISSUE TITLE
importd.s()

### ISSUE THREAD

**Issue by amitu** [amitu/importd#74]
Problem: Often I have to mirror on setting with another. Eg DEBUG and TEMPLATE_DEBUG are typically the same. Its not easy to say one setting should be equal to another when configuring setting via importd, but is easy when doing it via settings.py.

Solution:

```python
from importd import d, s

d(
    DEBUG=True,
    TEMPLATE_DEBUG=s("DEBUG")
)
```

**Comment by juancarlospaco** [comment]
:+1:
