### ISSUE TITLE
AttributeError: 'str' object has no attribute 'joinpath'

### ISSUE THREAD

**Issue by hitul007** [amitu/importd#77]
Getting below error when calling d.dotslash("../logs") 

```python
  File "/home/hitul/coverfox/env/rblog/local/lib/python2.7/site-packages/speaklater.py", line 186, in __getattr__
    return getattr(self.value, name)
AttributeError: 'str' object has no attribute 'joinpath'
make: *** [run] Error 1
```

**Comment by juancarlospaco** [comment]
Provide a snippet to test the error, just `d.dotslash("../logs")` does not make too much sense, 
or try to use std lib `os.path` or the new `pathlib` instead :grey_question:
